swagger: '2.0'
info:
  version: "1.0.0"
  title: theBuzz API
  description: Provide RESTful service to project social distribution.
  termsOfService: terms
  contact:
    name: CMPUT404WIN17BUMBLEBEE
    url: https://github.com/CMPUT404WIN17BUMBLEBEE
    email: shuming2@ualberta.ca
  license:
    name: Apache
    url: https://www.apache.org/licenses/LICENSE-2.0
host: 127.0.0.1:8000
basePath: /api
paths:
  /:
    get:
      summary: List API operations
      description: List API operations
      produces:
        - application/json
      responses:
        200:
          description: OK
        
  /posts:
    get:
      summary: POST
      description: Display post in JSON format
      produces: 
        - application/json
      responses:
        200:
          description: OK
          
  /profile:
    get:
      summary: PROFILE
      description: Display profile in JSON format
      produces: 
        - application/json
      responses:
        200:
          description: OK
          
  /comment:
    get:
      summary: COMMENT
      description: Display comment in JSON format
      produces: 
        - application/json
      responses:
        200:
          description: OK
          
  /author/posts:
    get:
      summary: Display author's post in JSON
      description: Display author's post in JSON
      responses:
        200:
          description: OK